# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce06334c3fadccebfecaae4cee03d563"
name = "loyalty program "
application_url = "https://loyalty-program-orjg.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,read_customers,write_orders,read_orders,read_products,write_products,write_themes,write_content,read_themes"

[auth]
redirect_urls = [ "https://loyalty-program-orjg.onrender.com/api/auth" ]
